module.exports = {
    Index: "/",
    UserBalance: "/user/balance",
    UserId: "/user/id",
    UserLinkRequests: "/user/link-requests",
    CreateAlias: "/create/alias",
    CreateReply: "/create/reply",
    CreateSend: "/create/send",
    CreateLike: "/create/like",
    CreateMute: "/create/mute",
    CreatePost: "/create/post",
    CreateLinkRequest: "/create/link/request",
    CreateLinkAccept: "/create/link/accept",
    CreateLinkFinish: "/create/link/finish",
    CreateTokenSend: "/create/token/send",
    CreateTopicFollow: "/create/topic/follow",
    CreateTopicPost: "/create/topic/post",
    PostReplies: "/post/replies",
    PostTopic: "/post/topic",
    ApiKeyGet: "/api/key/get",
    ApiKeyNew: "/api/key/new",
    ApiFundAddress: "/api/fund-address",
    ApiHistoryFunds: "/api/history/funds",
    ApiHistorySpends: "/api/history/spends",
    TxBroadcast: "/tx/broadcast",
    TxWait: "/tx/wait"
};
